// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmJmWdA4JjVruIASN2kAryjoVvB37iBIM',
    appId: '1:504597435298:web:6feb21bff3d7f5976358fb',
    messagingSenderId: '504597435298',
    projectId: 'chat-app-23320',
    authDomain: 'chat-app-23320.firebaseapp.com',
    storageBucket: 'chat-app-23320.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcvijdRYT6jS5yhmhOkuX7IChjwHPzEeY',
    appId: '1:504597435298:android:f0bf23af05a8d0fe6358fb',
    messagingSenderId: '504597435298',
    projectId: 'chat-app-23320',
    storageBucket: 'chat-app-23320.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOKL-wO2drGzxGVtPje5OoSVca9c1v3Mc',
    appId: '1:504597435298:ios:25ccfd857c314c266358fb',
    messagingSenderId: '504597435298',
    projectId: 'chat-app-23320',
    storageBucket: 'chat-app-23320.appspot.com',
    iosClientId: '504597435298-474k29mbol2r884mr1htk3ikug1ejsc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.betting1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOKL-wO2drGzxGVtPje5OoSVca9c1v3Mc',
    appId: '1:504597435298:ios:2ebfd35e5750b32e6358fb',
    messagingSenderId: '504597435298',
    projectId: 'chat-app-23320',
    storageBucket: 'chat-app-23320.appspot.com',
    iosClientId: '504597435298-37gorfphcth0e7q7hakgvja66jhp0dv8.apps.googleusercontent.com',
    iosBundleId: 'com.example.betting1.RunnerTests',
  );
}
